### ISSUE TITLE
TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by neerajwagh** [petrapoklukar/GeomCA#1]
Hi @petrapoklukar - thanks for releasing a well-organized implementation of GeomCA that's easy to follow with the paper! I'm trying to analyze representations of brain signals with it. 

Ran into an issue at line: https://github.com/petrapoklukar/GeomCA/blob/58c112b18a3fbc25544e39bb53b13da0ca738517/GeomCA.py#L381

TypeError: object of type 'generator' has no len()

Possible reasons:
- newer/incompatible versions of gudhi library (pip install gudhi=3.0.0 as per requirements.txt fails to find a matching version - I'm running 3.5.0)
- numerical issue due to numbers specified in config dict (not sure if certain R E inputs/thresholds lead to empty Python variables, leading to len( ) property errors - I'm using my own data)

Any thoughts on how I could debug this? https://gudhi.inria.fr/python/latest/simplex_tree_ref.html#gudhi.SimplexTree.get_skeleton seems like the object that is being invoked.

**Comment by neerajwagh** [comment]
Sorry this has an embarrassingly simple fix - converting the vrs generator to a list before using len()

vrs = list(vrs)

**Comment by petrapoklukar** [comment]
Hi @neerajwagh, 

really cool to hear you find GeomCA useful! I've seen the problem that you mentioned before, it comes from an updated version of the Gudhi library. I hope it works now but let me know if you need any more help with it.

You can also check out a newer version of the algorithm Delaunay Component Analysis (https://github.com/petrapoklukar/DCA) which works with GPU and gives a more precise manifold estimation.

Best, 
Petra

**Comment by neerajwagh** [comment]
@petrapoklukar  Thanks for pointing me to DCA! I'll check it out soon. Congrats on both the papers! :)

I could also use your advice on running GeomCA with ~80k points each in R and E sets. What configs would make the computation faster without impacting the measures too much? Would DCA be preferable in this case for speed?

From what I gather, the step that takes the longest is the epsilon-graph construction (computing pairwise distances between all points in RunionE) after an epsilon is estimated.

**Comment by petrapoklukar** [comment]
Hi @neerajwagh , 

you could try to first run DCA on all 80k points and see if you computational resources can handle it, just remember that you need a GPU for running it. If this doesn't work, you can try to speed up the approximation of the Delaunay graph which is the major bottleneck (as epsilon graph in GeomCA like you wrote). You can do so by choosing a lower T (number of rays used to approximate the Delaunay graph, you could try T = 10 ** 3) and/or a lower B (which reduces the number of edges in the graph, you could try B = 0.7 or even 0.5). I would start with lowering T and then lowering B.

Alternatively, you can also try to reduce the number of points - one option is to simply randomly sample around 50-60k points, the other one is to perform the geometric sparsification as done in GeomCA - and then run DCA/GeomCA on top of it. However, be sure to double check the resulting sets if you use the geometric sparsification as this can sometimes yield skewed results (we discuss this in both GeomCA and DCA papers).

Hope this helps!
Petra

**Comment by neerajwagh** [comment]
Thanks @petrapoklukar for the tips, and apologies for the delay in getting back to you! 

I was able to get DCA running with the GPU and restricted my experiments to a smaller set of data to get things moving quickly. Appreciate your time and help.

**Comment by petrapoklukar** [comment]
@neerajwagh great to hear this and good luck with your experiments. Feel free to reach out if you have any more questions!

Petra
